---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-image
  template:
    metadata:
      labels:
        app: nginx-image
    spec:
      containers:
        - name: nginx-image
          image: nginx:latest
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 80